// Auto-generated configuration file - DO NOT EDIT MANUALLY
// Generated by start.sh on Sun Jun 22 10:26:46 PDT 2025
window.ASL_CONFIG = {
    AI_SERVER_URL: 'http://localhost:8080',
    ASL_SERVER_URL: 'http://localhost:5001',
    GUN_RELAY_URL: 'http://localhost:8765/gun',
    WEB_SERVER_PORT: 8000,
    HTTPS_SERVER_PORT: 8443,
    AI_SERVER_AVAILABLE: false
};
console.log('ASL Command Center Configuration Loaded:', window.ASL_CONFIG);
